HotelReservationCodeFirst/HotelReservationCodeFirst/Controllers/StaffController.cs
using DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BizLogic;
using HotelReservationCodeFirst.Models;
using HotelReservationCodeFirst.Controllers;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace HotelReservationSystem.Controllers
{
    [Authorize(Roles = "staff")]
    public class StaffController : Controller
    {
        // GET: Staff
        public ActionResult Index()
        {          
                return View();           
        }

        // TODO: [StaffAuthorize]
        public ActionResult StaffViewInventory()
        {
            HashSet<Room> roomSet_copy = new HashSet<Room>();

            using (var context = new HotelDataModel())
            {
                /*
                foreach (Room r1 in context.RoomSet)
                {
                    Room r2 = new Room();
                    r2.type = r1.type;
                    r2.basicPrice = r1.type;
                    r2.occupancy = r1.occupancy;
                    r2.maxGuest = r1.maxGuest;
                    r2.description = r1.description;
                    r2.amanities = r1.amanities;
                    r2.inventory = r1.inventory;

                    roomSet_copy.Add(r2);
                }
                */
                var room_query0 = from r in context.RoomSet
                                  where r.type == 0
                                  select r;
                var room0 = room_query0.FirstOrDefault();
                if (room0 != null)
                    roomSet_copy.Add(room0);

                var room_query1 = from r in context.RoomSet
                                  where r.type == 1
                                  select r;
                var room1 = room_query1.FirstOrDefault();
                if (room1 != null)
                    roomSet_copy.Add(room1);

                var room_query2 = from r in context.RoomSet
                                  where r.type == 2
                                  select r;
                var room2 = room_query2.FirstOrDefault();
                if (room2 != null)
                    roomSet_copy.Add(room2);

                var room_query3 = from r in context.RoomSet
                                  where r.type == 3
                                  select r;
                var room3 = room_query3.FirstOrDefault();
                if (room3 != null)
                    roomSet_copy.Add(room3);

                return View(roomSet_copy);
            }
        }

        // TODO: [StaffAuthorize]
        public ActionResult EditInventory(int id)
        {
            using (var context = new HotelDataModel())
            {
                var room_query = from r in context.RoomSet
                                 where r.type == id
                                 select r;
                var room = room_query.FirstOrDefault();
                return View(room);
            }
        }

        // TODO: [StaffAuthorize]
        [HttpPost]
        public ActionResult EditInventory(Room r)
        {
            // TODO
            using (var context = new HotelDataModel())
            {
                var room_query = from ro in context.RoomSet
                                 where ro.type == r.type
                                 select ro;
                //    var room = room_query.FirstOrDefault();
                //    room.inventory = r.inventory;
                foreach (Room room in room_query)
                {
                    room.inventory = r.inventory;
                }

                context.SaveChanges();
            }
            return RedirectToAction("StaffViewInventory");
        }

        // TODO: StaffAu
        public ActionResult CheckInHelper(Reservation res)
        {
            var num = res.confirmationNum;
            Session["confirmationNum"] = num;
            return RedirectToAction("CheckIn");
        }

        // TODO: [StaffAuthorize]
        public ActionResult CheckIn()
        {
            //  int confirmationNum = Convert.ToInt32(Request.Cookies["confirmationNum"].ToString());
            int confirmationNum = Convert.ToInt32(Session["confirmationNum"].ToString());
            using (var context = new HotelDataModel())
            {
                var checkInReservation_query = from r in context.ReservationSet
                                               where r.confirmationNum == confirmationNum
                                               select r;
                var checkInReservation = checkInReservation_query.FirstOrDefault();
                //   HashSet<Reservation> rs = new HashSet<Reservation>();
                //   rs.Add(checkInReservation);
                //   return View(rs);
                return View(checkInReservation);
            }
        }

        // TODO: [StaffAuthorize]
        [HttpPost]
        public ActionResult CheckIn(Reservation reservation)
        {
            int confirmationNum = Convert.ToInt32(Session["confirmationNum"].ToString());
            using (var context = new HotelDataModel())
            {
                var checkInReservation_query = from r in context.ReservationSet
                                               where r.confirmationNum == confirmationNum
                                               select r;
                var checkInReservation = checkInReservation_query.FirstOrDefault();
                checkInReservation.checkedIn = true;
                checkInReservation.checkInDate = DateTime.Now.Date;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // TODO: StaffAu
        public ActionResult CheckOutHelper(Reservation res)
        {
            var num = res.confirmationNum;
            Session["confirmationNum"] = num;
            return RedirectToAction("CheckOut");
        }
        // TODO: [StaffAuthorize]
        public ActionResult CheckOut()
        {
            //  int confirmationNum = Convert.ToInt32(Request.Cookies["confirmationNum"].ToString());
            int confirmationNum = Convert.ToInt32(Session["confirmationNum"].ToString());
            using (var context = new HotelDataModel())
            {
                var checkOutReservation_query = from r in context.ReservationSet
                                                where r.confirmationNum == confirmationNum
                                                select r;
                var checkOutReservation = checkOutReservation_query.FirstOrDefault();
                // HashSet<Reservation> rs = new HashSet<Reservation>();
                // rs.Add(checkOutReservation);
                // return View(rs);
                return View(checkOutReservation);
            }
        }

        // TODO: [StaffAuthorize]
        [HttpPost]
        public ActionResult CheckOut(Reservation reservation)
        {
            int confirmationNum = Convert.ToInt32(Session["confirmationNum"].ToString());
            using (var context = new HotelDataModel())
            {
                var checkOutReservation_query = from r in context.ReservationSet
                                                where r.confirmationNum == confirmationNum
                                                select r;
                var checkOutReservation = checkOutReservation_query.FirstOrDefault();
                checkOutReservation.checkedOut = true;
                checkOutReservation.checkOutDate = DateTime.Now.Date;
                context.SaveChanges();

                /*5/8: When check out, decrease today's occupancy */
                var room_query = from ro in context.RoomSet
                                 where ro.type == checkOutReservation.Room_type.type &&
                                 ro.date.Year == DateTime.Now.Year &&
                                 ro.date.Month == DateTime.Now.Month &&
                                 ro.date.Day == DateTime.Now.Day
                                 select ro;
                var roomTd = room_query.FirstOrDefault();
                roomTd.occupancy--;
                /*5/8: */

                // put info into Session for billing
                Session["svConfirmationNum"] = checkOutReservation.confirmationNum;
                int rt = checkOutReservation.confirmationNum;
                if (rt == 0)
                {
                    Session["svRoomType"] = "King";
                }
                else if (rt == 1)
                {
                    Session["svRoomType"] = "Queen";
                }
                else if (rt == 2)
                {
                    Session["svRoomType"] = "Double";
                }
                else
                {
                    Session["svRoomType"] = "Suite";
                }
                Session["svCheckInDate"] = checkOutReservation.checkInDate;
                Session["svCheckOutDate"] = checkOutReservation.checkOutDate;
                Session["svBillingFirstName"] = checkOutReservation.billingFirstName;
                Session["svBillingLastName"] = checkOutReservation.billingLastName;
                Session["svPhone"] = checkOutReservation.phone;
                Session["svEmail"] = checkOutReservation.email;

                double duration = (DateTime.Now - checkOutReservation.checkInDate).TotalDays - 1;
                if (duration <= 0)
                {
                    duration = 1;
                }
                double price = 0;
                if (checkOutReservation.Room_type.type == 0)
                {
                    price = 100;
                }
                else if (checkOutReservation.Room_type.type == 1)
                {
                    price = 150;
                }
                else if (checkOutReservation.Room_type.type == 2)
                {
                    price = 200;
                }
                else
                {

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/CheckIn.cshtml
@model DataModel.Reservation

@{
    ViewBag.Title = "CheckIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Check In</h2>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.checkInDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkInDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkOutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkOutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkedIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkedIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkedOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkedOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.billingFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.billingFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.billingLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.billingLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName4)
        </dd>

       

    </dl>
</div>
<p>
    @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Check In" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</p>

@Html.ActionLink("Back to List", "Index")

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/CheckOut.cshtml
@model DataModel.Reservation

@{
    ViewBag.Title = "CheckOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Check Out</h2>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.checkOutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkOutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkOutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkOutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkedIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkedIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checkedOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checkedOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.billingFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.billingFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.billingLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.billingLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName4)
        </dd>

        

    </dl>
</div>
<p>
    @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Check Out" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</p>

@Html.ActionLink("Back to List", "Index")

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/CurrentOccupancy.cshtml
@{
    ViewBag.Title = "CurrentOccupancy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Current Occupancy</h2>

<div><label>King Room Occupancy:</label>  @ViewBag.kcount</div>
<div><label>King Room Occupancy Percentage:</label>  @ViewBag.kpercent</div>

<div>
    <label>Queen Room Occupancy:</label>  @ViewBag.qcount
</div>
<div>
    <label>Queen Room Occupancy Percentage:</label>  @ViewBag.qpercent
</div>
<div>
    <label>Double Room Occupancy:</label>  @ViewBag.dcount
</div>
<div>
    <label>Double Room Occupancy Percentage:</label>  @ViewBag.dpercent
</div>
<div>
    <label>Suite Occupancy:</label>  @ViewBag.scount
</div>
<div>
    <label>Suite Occupancy Percentage:</label>  @ViewBag.spercent
</div>

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/EditInventory.cshtml
@model DataModel.Room

@{
    ViewBag.Title = "EditInventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Inventory</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.type)

        <div class="form-group">
            @if (Model.type == 0)
            {
                @Html.TextBox("RoomTypeTextBox", "King Bed Rooms", new { @class = "control-label col-md-2" })
            }
            else if (Model.type == 1)
            {
                @Html.TextBox("RoomTypeTextBox", "Queen Bed Rooms", new { @class = "control-label col-md-2" })
            }
            else if (Model.type == 2)
            {
                @Html.TextBox("RoomTypeTextBox", "Double Bed Rooms", new { @class = "control-label col-md-2" })
            }
            else
            {
                @Html.TextBox("RoomTypeTextBox", "Suites", new { @class = "control-label col-md-2" })
            }

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.inventory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "StaffViewInventory")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/FOQuery.cshtml
@{
    ViewBag.Title = "FOQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Future Occupancy</h2>

<div><label>King Room Occupancy:</label>  @ViewBag.kcount</div>
<div><label>King Room Occupancy Percentage:</label>  @ViewBag.kpercent</div>

<div>
    <label>Queen Room Occupancy:</label>  @ViewBag.qcount
</div>
<div>
    <label>Queen Room Occupancy Percentage:</label>  @ViewBag.qpercent
</div>
<div>
    <label>Double Room Occupancy:</label>  @ViewBag.dcount
</div>
<div>
    <label>Double Room Occupancy Percentage:</label>  @ViewBag.dpercent
</div>
<div>
    <label>Suite Occupancy:</label>  @ViewBag.scount
</div>
<div>
    <label>Suite Occupancy Percentage:</label>  @ViewBag.spercent

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/FutureOccupancy.cshtml
@model DataModel.FOccupancy

@{
    ViewBag.Title = "FutureOccupancy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Future Occupancy</h2>

@using (Html.BeginForm("FOQuery", "Staff", FormMethod.Post))
{
    <h1>Year: </h1>
    <div>
        @Html.TextBoxFor(model => model.Year)
    @Html.ValidationMessageFor(model => model.Year)
</div>
<div>
    <h1>Month: </h1>
    @Html.TextBoxFor(model => model.Month)
    @Html.ValidationMessageFor(model => model.Month)
</div>
<div>
    <h1>Day: </h1>
    @Html.TextBoxFor(model => model.Day)
    @Html.ValidationMessageFor(model => model.Day)
</div>
<div><button type="submit">Check</button></div>

}

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/GenerateBill.cshtml
@{
    ViewBag.Title = "GenerateBill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bill</h2>

<br />

<!--Display the reservation information-->
<div>
    <div>
        <h3>Confirmation number: @(Session["svConfirmationNum"])</h3>
    </div>
    <div>
        <h4>Room type: @(Session["svConfirmationNum"])</h4>
    </div>
    <div>
        <h4>Check in date: @(Session["svCheckInDate"])</h4>
    </div>
    <div>
        <h4>Check out date: @(Session["svCheckOutDate"])</h4>
    </div>
    <div>
        <h4>Billing guest first name: @(Session["svBillingFirstName"])</h4>
    </div>
    <div>
        <h4>Billing guest last name: @(Session["svBillingLastName"])</h4>
    </div>
    <div>
        <h4>Phone number: @(Session["svPhone"])</h4>
    </div>
    <div>
        <h4>Email address: @(Session["svEmail"])</h4>
    </div>
    <div>
        <h3>Total payment: @(Session["payment"])</h3>
    </div>

</div>

<br />

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/Index.cshtml
@model DataModel.Reservation
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Staff Page</h2>

<div>

    <h1>@Html.ActionLink("Check Inventory", "StaffViewInventory")</h1>
    <h1>@Html.ActionLink("Occupancy", "Occupancy")</h1>
    <h1>@Html.ActionLink("Today's upcoming check-in", "TodayCheckIn")</h1>
    <h1>@Html.ActionLink("Today's upcoming check-out", "TodayCheckOut")</h1>
    <h1>@Html.ActionLink("Auto check-out for outdated reservation", "AutoCheckOut")</h1>


    @using (Html.BeginForm("CheckInHelper", "Staff", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.confirmationNum)
        @Html.ValidationMessageFor(model => model.confirmationNum)
        <button type="submit">Check In</button>
    }

    @using (Html.BeginForm("CheckOutHelper", "Staff", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.confirmationNum)
        @Html.ValidationMessageFor(model => model.confirmationNum)
        <button type="submit">Check Out</button>
    }
</div>

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/Occupancy.cshtml
@{
    ViewBag.Title = "Occupancy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Occupancy</h2>

<div><h1>@Html.ActionLink("Current Occupancy", "CurrentOccupancy")</h1></div>

<div><h1>@Html.ActionLink("Future Occupancy", "FutureOccupancy")</h1></div>

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/StaffViewInventory.cshtml
@model IEnumerable<DataModel.Room>

@{
    ViewBag.Title = "StaffViewInventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inventory</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.inventory)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.type == 0)
                {
                    <h1>King Bed Rooms</h1>
                }
                else if (item.type == 1)
                {
                    <h1>Queen Bed Rooms</h1>
                }
                else if (item.type == 2)
                {
                    <h1>Double Bed Rooms</h1>
                }
                else
                {
                    <h1>Suites</h1>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.inventory)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditInventory", new { id = item.type })
            </td>
        </tr>
    }

</table>

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Staff/TodayCheckIn.cshtml
@model IEnumerable<DataModel.Reservation>

@{
    ViewBag.Title = "TodayCheckIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Today's Upcoming Check-In</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.checkInDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.checkOutDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.checkedIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.checkedOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.billingFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.billingLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName4)
        </th>      
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.checkInDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.checkOutDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.checkedIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.checkedOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.zip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.billingFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.billingLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName4)
            </td>
        </tr>
    }

</table>