HotelReservationCodeFirst/HotelReservationCodeFirst/Models/ReserveViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

using System.Web.Mvc; //for SelectListItem

namespace HotelReservationCodeFirst.Models
{
    //view models for Reserve view 
    public class ReserveViewModel
    {
        //[Required]
        //public string roomType { get; set; }

        //public IEnumerable<SelectListItem> rooms { get; set; }

        //available room numbers of each type of the room
        public int kingLeft { get; set; }
        public int queenLeft { get; set; }
        public int doubleLeft { get; set; }
        public int suiteLeft { get; set; }


        [Required]
        public DateTime checkInDate { get; set; }

        [Required]
        public DateTime checkOutDate { get; set; }

        [Display(Name = "King")]
        public string King;

        [Display(Name = "Queen")]
        public string Queen;

        [Display(Name = "Double")]
        public string Double;

        [Display(Name = "Suite")]
        public string Suite;

        [Required]
        public string roomType { get; set; }

        [Required]
        [Display(Name = "First name of guest 1:")]
        public string Guest1FirstName { set; get; }

        [Required]
        [Display(Name = "Last name of guest 1:")]
        public string Guest1LastName { set; get; }

        [Display(Name = "First name of guest 2:")]
        public string Guest2FirstName { set; get; }

        [Display(Name = "Last name of guest 2:")]
        public string Guest2LastName { set; get; }

        [Display(Name = "First name of guest 3:")]
        public string Guest3FirstName { set; get; }

        [Display(Name = "Last name of guest 3:")]
        public string Guest3LastName { set; get; }

        [Display(Name = "First name of guest 4:")]
        public string Guest4FirstName { set; get; }

        [Display(Name = "Last name of guest 4:")]
        public string Guest4LastName { set; get; }

    }

    //view model for confirming reservation view
    public class ConfirmReservationViewModel
    {
        [Required]
        [Display(Name = "First name")]
        public string firstName { set; get; }

        [Required]
        [Display(Name = "Last name")]
        public string lastName { set; get; }

        [Required]
        [Display(Name = "Address")]
        public string address { set; get; }

        [Required]
        [Display(Name = "City")]
        public string city { set; get; }

        [Required]
        [Display(Name = "State")]
        public string state { set; get; }

        [Required]
        [Display(Name = "Zip code")]
        public string zipCode { set; get; }

        [Required]
        [Display(Name = "Email address")]
        public string email { set; get; }

        [Required]
        [Display(Name = "Telephone number")]
        public string phone { set; get; }

    }

    public class ReservationInfoViewModel
    {
        //the total prize of the resrevation
        public double prize { get; set; }

    }
}

HotelReservationCodeFirst/HotelReservationCodeFirst/Controllers/ReserveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HotelReservationCodeFirst.Models;

using DataModel;

using BizLogic;
using Microsoft.AspNet.Identity;

namespace HotelReservationCodeFirst.Controllers
{
    public class ReserveController : Controller
    {

        //Get
        public ActionResult Index()
        {
            string cIn = "05/10/2017";
            string cOut = "05/10/2017";

            //get the check in/out date
            DateTime checkIn = Convert.ToDateTime(cIn);
            DateTime checkOut = Convert.ToDateTime(cOut);

            //call bizLogic to get the number of available rooms
            ReserveViewModel model = new ReserveViewModel();
            HotelReservationExtensions logic = new HotelReservationExtensions();

            //add room series from checkn in date to check out date to the database
            logic.addRoomSeries(0, checkIn, checkOut);
            logic.addRoomSeries(1, checkIn, checkOut);
            logic.addRoomSeries(2, checkIn, checkOut);
            logic.addRoomSeries(3, checkIn, checkOut);

            //check the number of each type of rooms available
            model.kingLeft = logic.roomAvailable(0, checkIn, checkOut);
            model.queenLeft = logic.roomAvailable(1, checkIn, checkOut);
            model.doubleLeft = logic.roomAvailable(2, checkIn, checkOut);
            model.suiteLeft = logic.roomAvailable(3, checkIn, checkOut);


            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ReserveViewModel model)
        {
            string cIn = Request.Cookies["CheckInDate"].Value;
            string cOut = Request.Cookies["CheckOutDate"].Value;

            //hard code the check in/out date
            Session["CheckInDate"] = cIn;
            Session["CheckOutDate"] = cOut;


            //Response.Cookies["Reservation"]["CheckInDate"] = "05/09/2017";
            //Response.Cookies["Reservation"]["CheckOutDate"] = "05/12/2017";
            HotelReservationExtensions logic = new HotelReservationExtensions();
            DateTime checkIn = Convert.ToDateTime(cIn);
            DateTime checkOut = Convert.ToDateTime(cOut);

            logic.addRoomSeries(0, checkIn, checkOut);
            logic.addRoomSeries(1, checkIn, checkOut);
            logic.addRoomSeries(2, checkIn, checkOut);
            logic.addRoomSeries(3, checkIn, checkOut);


            //add room type to cookies
            Response.Cookies["Reservation"]["RoomType"] = model.roomType;
            Session["RoomType"] = model.roomType;

            Response.Cookies["Reservation"]["Guest1FirstName"] = model.Guest1FirstName;
            Response.Cookies["Reservation"]["Guest1LastName"] = model.Guest1LastName;

            Response.Cookies["Reservation"]["Guest2FirstName"] = model.Guest2FirstName;
            Response.Cookies["Reservation"]["Guest2LastName"] = model.Guest2LastName;

            Response.Cookies["Reservation"]["Guest3FirstName"] = model.Guest3FirstName;
            Response.Cookies["Reservation"]["Guest3LastName"] = model.Guest3LastName;

            Response.Cookies["Reservation"]["Guest4FirstName"] = model.Guest3FirstName;
            Response.Cookies["Reservation"]["Guest4LastName"] = model.Guest3LastName;

            return RedirectToAction("ConfirmReservation");

        }

        public ActionResult ConfirmReservation()
        {
            //for the grid view
            var northwind = new HotelDataModel();
            //Get the Products entities and add them to the ViewBag.
            ViewBag.Rooms = northwind.RoomSet;


            return View();
        }

        [HttpPost]
        //page for confirming reservation and setting billing information
        public ActionResult ConfirmReservation(ConfirmReservationViewModel model)
        {

            Random random = new Random();
            int confirmationNum = random.Next(1, 1000000);

            //hard code the check in/out date
            //DateTime checkInDate = Convert.ToDateTime(Request.Cookies["Reservation"]["CheckInDate"]);
            //DateTime checkOutDate = Convert.ToDateTime(Request.Cookies["Reservation"]["CheckOutDate"]);

            DateTime checkInDate = Convert.ToDateTime((string)Session["CheckInDate"]);
            DateTime checkOutDate = Convert.ToDateTime((string)Session["CheckOutDate"]);


            bool checkedIn = false;
            bool checkedOut = false;
            string address = model.address;
            string city = model.city;
            string state = model.state;
            string zip = model.zipCode;
            string email = model.email;
            string phone = model.phone;

            string billingFirstName = model.firstName;
            string billingLastName = model.lastName;

            //hard code the rest names
            string firstName2 = "firstName2";
            string firstName3 = "firstName3";
            string firstName4 = "firstName4";
            string lastName2 = "lastName2";
            string lastName3 = "lastName3";
            string lastName4 = "lastName4";
            

            //hard code the room type 
            string room = Request.Cookies["Reservation"]["RoomType"];
            int Room_type = 0;
            if(room == "king")
            {
                Room_type = 0;
            }
            else if(room == "queen")
            {
                Room_type = 1;
            }
            else if(room == "double")
            {
                Room_type = 2;
            }
            else
            {
                Room_type = 3;
            }

            //save billing information to Cookies
            //dangerous!
            Response.Cookies["Reservation"]["FirstName"] = billingFirstName;
            Response.Cookies["Reservation"]["LastName"] = billingLastName;

            Response.Cookies["Reservation"]["ConfirmationNumber"] = ""+ confirmationNum;
            Response.Cookies["Reservation"]["BillingFirstName"] = model.firstName;
            Response.Cookies["Reservation"]["BillingLastName"] = model.lastName;
            Response.Cookies["Reservation"]["Phone"] = model.phone;
            Response.Cookies["Reservation"]["Email"] = model.email;


            //add the reservation to database using business logic
            HotelReservationExtensions biz = new HotelReservationExtensions();
            var userId = User.Identity.GetUserId();
            Reservation reservation = biz.customerReserve(confirmationNum, checkInDate, checkOutDate, checkedIn, checkedOut,
                address, city, state, zip, email, phone, billingFirstName, billingLastName, firstName2,
                lastName2, firstName3, lastName3, firstName4, lastName4, Room_type, userId);

            //change the occupancy of the room
            biz.changeOccupancy(Room_type, checkInDate, checkOutDate);

            //if user is logged in, add this reservation to the user
            bool loggedIn = (System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;
            if (loggedIn)
            {
                string id = User.Identity.GetUserId();
                CustomerController cc = new CustomerController();
                cc.addReservation(id, reservation);
            }

            return RedirectToAction("ReservationInfo");

        }

        //Get
        public ActionResult ReservationInfo(ReservationInfoViewModel model)
        {
            DateTime checkIn = Convert.ToDateTime((string)Session["CheckIndate"]);
            DateTime checkOut = Convert.ToDateTime((string)Session["CheckOutdate"]);

            double day = (checkOut.Date - checkIn.Date).TotalDays;

            //hard code the total prize of this reservation
            int room_type = 0;

            if ((string)Session["RoomType"] == "king")
            {
                room_type = 0;
            }
            else if ((string)Session["RoomType"] == "Queen")
            {
                room_type = 1;
            }
            else if ((string)Session["RoomType"] == "Double")
            {
                room_type = 2;
            }
            else
            {
                room_type = 3;
            }

            HotelReservationExtensions biz = new HotelReservationExtensions();
            model.prize = (int)biz.getTotalRateForDayRange(room_type, checkIn, checkOut);
            return View(model);
        }

    }
}

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Reserve/ConfirmReservation.cshtml
@using HotelReservationCodeFirst.Models
@using DataModel
@model ConfirmReservationViewModel


@{
    ViewBag.Title = "ConfirmReservation";
}

<h2>Confirm Reservation</h2>

<!--Tabular list of the room rate on each night of stay-->
<h3>Rates on each night</h3>

@(Html.Kendo().Grid((IEnumerable<Room>)ViewBag.Rooms) //Bind the grid to ViewBag.Products
            .Name("grid")
            .Columns(columns =>
            {
                ////Create a column bound to the ProductID property.
                //columns.Bound(product => product.ProductID);
                ////Create a column bound to the ProductName property.
                //columns.Bound(product => product.ProductName);
                ////Create a column bound to the UnitsInStock property.
                //columns.Bound(product => product.UnitsInStock);
                columns.Bound(room => room.type);
                columns.Bound(room => room.inventory);
                columns.Bound(room => room.occupancy);
                columns.Bound(room => room.basicPrice);
                columns.Bound(room => room.date);
            })
            .Pageable() //Enable the paging.
            .Sortable() //Enable the sorting.
)

<br/>

<!--Enter the billing information-->
<h3>Enter billing information</h3>

@using (Html.BeginForm("ConfirmReservation", "Reserve", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<div class="row">

            <div class="form-group">
                @Html.LabelFor(m => m.firstName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.firstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.firstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.lastName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.lastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.lastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.address, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.city, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.city, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.city, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.state, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.state, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.state, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.zipCode, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.zipCode, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.zipCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.email, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.phone, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.phone, "", new { @class = "text-danger" })
                </div>
            </div>
</div>




<br />

<!--Place reservation order-->
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Place order" class="btn btn-default" />
    </div>
</div>

}

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Reserve/Index.cshtml
@using HotelReservationCodeFirst.Models
@model ReserveViewModel

@{
    ViewBag.Title = "Index";
}


<h2>Reserve a new room</h2>

    <hr />

    <h3>Select check in/out date</h3>
    @(Html.Kendo().DatePicker()
            .Name("datepicker1") //The name of the DatePicker is mandatory. It specifies the "id" attribute of the widget.
            .Min(new DateTime(1900, 1, 1)) //Set the min date of the DatePicker.
            .Max(new DateTime(2099, 12, 31)) //Set the min date of the DatePicker.
            .Value(DateTime.Today) //Set the value of the DatePicker.
            .Events(e => e
                .Open("datepicker1_open")
                .Close("datepicker1_close")
                .Change("datepicker1_change")
          )
    )

    

    <hr/>

    <h3>Select check out date</h3>
    @(Html.Kendo().DatePicker()
            .Name("datepicker2") //The name of the DatePicker is mandatory. It specifies the "id" attribute of the widget.
            .Min(new DateTime(1900, 1, 1)) //Set the min date of the DatePicker.
            .Max(new DateTime(2099, 12, 31)) //Set the min date of the DatePicker.
            .Value(DateTime.Today) //Set the value of the DatePicker.
            .Events(e => e
                .Open("datepicker2_open")
                .Close("datepicker2_close")
                .Change("datepicker2_change")
          )
    )

    
    <!--Event handler-->
    <script>
        function datepicker1_open() {
            //Handle the open event
        }

        function datepicker1_close()   {
            //Handle the close event
        }

        function datepicker1_change() {
            //Handle the change event
            document.cookie = "CheckInDate=" + kendo.toString(this.value(), 'd');
        }

        function datepicker2_open() {
            //Handle the open event
        }

        function datepicker2_close() {
            //Handle the close event
        }

        function datepicker2_change() {
            //Handle the change event
            document.cookie = "CheckOutDate=" + kendo.toString(this.value(), 'd');
        }

    </script>


@*<div class="container">
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker6'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker7'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
            $.cookie('CheckInDate', ('#datetimepicker7').data("DateTimePicker").minDate(e.date), 7300);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
            $.cookie('CheckOutDate', ('#datetimepicker6').data("DateTimePicker").maxDate(e.date), 7300);
        });
    });
</script>*@

<hr/>

<!--Display room availability-->
 <div>
     <div>
         <h4>Number of Queen bed room available: @Model.queenLeft.ToString()</h4>
     </div>
     <div>
         <h4>Number of King bed room available: @Model.kingLeft.ToString()</h4>
     </div>
     <div>
         <h4>Number of Double bed room available: @Model.doubleLeft.ToString()</h4>
     </div>
     <div>
         <h4>Number of Suite room available: @Model.suiteLeft.ToString()</h4>
     </div>
 </div>


    <hr/>

    <h3>Select room type</h3>

<!--Select the room type-->
@using (Html.BeginForm("Index", "Reserve", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">

        <div class="form-group">
            @Html.LabelFor(m => m.King, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.roomType, "king")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Queen, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.roomType, "queen")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Double, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.roomType, "double")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Suite, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.RadioButtonFor(m => m.roomType, "suite")
            </div>
        </div>

        @*</div>*@

        <hr />

        <h3>Enter guests' names </h3>

            @*<div class="row">*@
                @*<div class="col-md-8">*@
                @*<section id="loginForm">*@

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest1FirstName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest1FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest1FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest1LastName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest1LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest1LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest2FirstName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest2FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest2FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest2LastName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest2LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest2LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest3FirstName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest3FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest3FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest3LastName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest3LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest3LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest4FirstName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest4FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest4FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Guest4LastName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Guest4LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Guest4LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>    


    <br />

    <!--Button for proceed to confirm reservation-->
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Proceed to check out" class="btn btn-default" />
        </div>
    </div>

    <br />

  }



 

HotelReservationCodeFirst/HotelReservationCodeFirst/Views/Reserve/ReservationInfo.cshtml
@using HotelReservationCodeFirst.Models
@model ReservationInfoViewModel

@{
    ViewBag.Title = "ReservationInfo";
}

<h2>Reservation complete!</h2>

<br/>

<!--Display the reservation information-->
<div>
    <div>
        <h3>Confirmation number: @Request.Cookies["Reservation"]["ConfirmationNumber"]</h3>
    </div>
    <div>
        <h4>Billing first name: @Request.Cookies["Reservation"]["FirstName"]</h4>
    </div>
    <div>
        <h4>Billing last name: @Request.Cookies["Reservation"]["LastName"]</h4>
    </div>
    <div>
        <h4>Room type: @(Session["RoomType"])</h4>
    </div>
    <div>
        <h4>Check in date: @(Session["CheckInDate"])</h4>
    </div>
    <div>
        <h4>Check out date: @(Session["CheckOutDate"])</h4>
    </div>

    <div>
        <h4>Phone number: @Request.Cookies["Reservation"]["Phone"]</h4>
    </div>
    <div>
        <h4>Email address: @Request.Cookies["Reservation"]["Email"]</h4>
    </div>
    <div>
        <h3>Total payment: @Model.prize.ToString() </h3>
    </div>

</div>

<br/>